-- Optional manual import of the original Cameo catalog.
-- The updated admin.html imports missing catalog items automatically after owner login.
-- This SQL is provided only as a manual alternative. Existing matching name/category rows are not handled by this file.

insert into public.products (name,category,price,sizes,colors,image_url,in_stock,sort_order) values
('Urban Chic Jumpsuit','Jumpsuits',null,'{}'::text[],'{}'::text[],'assets/products/p001.jpeg',true,1),
('Weekend Muse Jumpsuit','Jumpsuits',null,'{}'::text[],'{}'::text[],'assets/products/p002.jpeg',true,2),
('Ivory Daydream Dress','Dresses',800,'{}'::text[],'{}'::text[],'assets/products/p003.jpeg',true,3),
('City Bloom Midi Dress','Dresses',800,'{}'::text[],'{}'::text[],'assets/products/p004.jpeg',true,4),
('Rosé Evening Dress','Dresses',800,'{}'::text[],'{}'::text[],'assets/products/p005.jpeg',true,5),
('Sienna Wrap Dress','Dresses',800,'{}'::text[],'{}'::text[],'assets/products/p006.jpeg',true,6),
('Sunday Brunch Dress','Dresses',800,'{}'::text[],'{}'::text[],'assets/products/p007.jpeg',true,7),
('Moonlight Mini Dress','Dresses',800,'{}'::text[],'{}'::text[],'assets/products/p008.jpeg',true,8),
('Willow Summer Dress','Dresses',800,'{}'::text[],'{}'::text[],'assets/products/p009.jpeg',true,9),
('Bella Statement Dress','Dresses',800,'{}'::text[],'{}'::text[],'assets/products/p010.jpeg',true,10),
('Amara Day Dress','Dresses',800,'{}'::text[],'{}'::text[],'assets/products/p011.jpeg',true,11),
('Celine Party Dress','Dresses',800,'{}'::text[],'{}'::text[],'assets/products/p012.jpeg',true,12),
('Everyday Muse Top','Tops',800,'{}'::text[],'{}'::text[],'assets/products/p013.jpeg',true,13),
('Soft Bloom Top','Tops',800,'{}'::text[],'{}'::text[],'assets/products/p014.jpeg',true,14),
('Satin Glow Top','Tops',1850,'{}'::text[],'{}'::text[],'assets/products/p015.jpeg',true,15),
('Midnight Charm Top','Tops',1850,'{}'::text[],'{}'::text[],'assets/products/p016.jpeg',true,16),
('Pearl Detail Top','Tops',1850,'{}'::text[],'{}'::text[],'assets/products/p017.jpeg',true,17),
('Weekend Luxe Top','Tops',1850,'{}'::text[],'{}'::text[],'assets/products/p018.jpeg',true,18),
('Blush Essential Top','Tops',null,'{}'::text[],'{}'::text[],'assets/products/p019.jpeg',true,19),
('City Chic Top','Tops',null,'{}'::text[],'{}'::text[],'assets/products/p020.jpeg',true,20),
('Daisy Casual Top','Tops',750,'{}'::text[],'{}'::text[],'assets/products/p021.jpeg',true,21),
('Classic Rib Top','Tops',750,'{}'::text[],'{}'::text[],'assets/products/p022.jpeg',true,22),
('Coffee Date Top','Tops',750,'{}'::text[],'{}'::text[],'assets/products/p023.jpeg',true,23),
('Modern Muse Top','Tops',750,'{}'::text[],'{}'::text[],'assets/products/p024.jpeg',true,24),
('Everyday Essential Tee','Tshirts',300,'{}'::text[],'{}'::text[],'assets/products/p025.jpeg',true,25),
('Weekend Graphic Tee','Tshirts',300,'{}'::text[],'{}'::text[],'assets/products/p026.jpeg',true,26),
('Easy Street Tee','Tshirts',300,'{}'::text[],'{}'::text[],'assets/products/p027.jpeg',true,27),
('Minimal Mood Tee','Tshirts',300,'{}'::text[],'{}'::text[],'assets/products/p028.jpeg',true,28),
('City Girl Tee','Tshirts',300,'{}'::text[],'{}'::text[],'assets/products/p029.jpeg',true,29),
('Relaxed Fit Tee','Tshirts',300,'{}'::text[],'{}'::text[],'assets/products/p030.jpeg',true,30),
('Daily Edit Tee','Tshirts',300,'{}'::text[],'{}'::text[],'assets/products/p031.jpeg',true,31),
('Off-Duty Tee','Tshirts',300,'{}'::text[],'{}'::text[],'assets/products/p032.jpeg',true,32),
('Classic Crew Tee','Tshirts',300,'{}'::text[],'{}'::text[],'assets/products/p033.jpeg',true,33),
('Casual Muse Tee','Tshirts',300,'{}'::text[],'{}'::text[],'assets/products/p034.jpeg',true,34),
('Dreamy Comfort Nightsuit','Nightsuits',799,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p035.jpeg',true,35),
('Moonlight Lounge Set','Nightsuits',799,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p036.jpeg',true,36),
('Soft Touch Nightsuit','Nightsuits',799,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p037.jpeg',true,37),
('Cozy Bloom Nightsuit','Nightsuits',799,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p038.jpeg',true,38),
('Weekend Lounge Nightsuit','Nightsuits',799,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p039.jpeg',true,39),
('Cloud Comfort Nightsuit','Nightsuits',799,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p040.jpeg',true,40),
('Sweet Dreams Nightsuit','Nightsuits',799,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p041.jpeg',true,41),
('Pleated Midi Skirt','Skirts',1250,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p042.jpeg',true,42),
('Satin Evening Skirt','Skirts',1250,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p043.jpeg',true,43),
('Floral Day Skirt','Skirts',1250,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p044.jpeg',true,44),
('Classic A-Line Skirt','Skirts',1250,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p045.jpeg',true,45),
('Chic Mini Skirt','Skirts',1250,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p046.jpeg',true,46),
('Flowy Maxi Skirt','Skirts',1150,ARRAY['FREE UPTO 32 WAIST']::text[],'{}'::text[],'assets/products/p047.jpeg',true,47),
('High-Waist Midi Skirt','Skirts',1150,ARRAY['FREE UPTO 32 WAIST']::text[],'{}'::text[],'assets/products/p048.jpeg',true,48),
('Weekend Wrap Skirt','Skirts',1150,ARRAY['FREE UPTO 32 WAIST']::text[],'{}'::text[],'assets/products/p049.jpeg',true,49),
('Soft Pleated Skirt','Skirts',1150,ARRAY['FREE UPTO 32 WAIST']::text[],'{}'::text[],'assets/products/p050.jpeg',true,50),
('City Mini Skirt','Skirts',1150,ARRAY['FREE UPTO 32 WAIST']::text[],'{}'::text[],'assets/products/p051.jpeg',true,51),
('Everyday A-Line Skirt','Skirts',1150,ARRAY['FREE UPTO 32 WAIST']::text[],'{}'::text[],'assets/products/p052.jpeg',true,52),
('Statement Maxi Skirt','Skirts',1150,ARRAY['FREE UPTO 32 WAIST']::text[],'{}'::text[],'assets/products/p053.jpeg',true,53),
('Brunch Ready Skirt','Skirts',1150,ARRAY['FREE UPTO 32 WAIST']::text[],'{}'::text[],'assets/products/p054.jpeg',true,54),
('Modern Midi Skirt','Skirts',1250,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p055.jpeg',true,55),
('Elegant Flare Skirt','Skirts',1250,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p056.jpeg',true,56),
('Classic Wrap Skirt','Skirts',1250,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p057.jpeg',true,57),
('Cameo Signature Skirt','Skirts',1250,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p058.jpeg',true,58),
('Signature Co-ord Set','Two-pc set',2550,ARRAY['M','L']::text[],'{}'::text[],'assets/products/p059.jpeg',true,59),
('Luxe Day Co-ord','Two-pc set',2550,ARRAY['M','L']::text[],'{}'::text[],'assets/products/p060.jpeg',true,60),
('Modern Muse Two-Piece','Two-pc set',2550,ARRAY['M','L']::text[],'{}'::text[],'assets/products/p061.jpeg',true,61),
('Brunch Ready Co-ord','Two-pc set',2150,ARRAY['M']::text[],'{}'::text[],'assets/products/p062.jpeg',true,62),
('City Chic Co-ord','Two-pc set',1850,ARRAY['M','L','XL']::text[],'{}'::text[],'assets/products/p063.jpeg',true,63),
('Soft Glam Two-Piece','Two-pc set',1850,ARRAY['M','L','XL']::text[],'{}'::text[],'assets/products/p064.jpeg',true,64),
('Weekend Statement Set','Two-pc set',2250,ARRAY['M','L']::text[],'{}'::text[],'assets/products/p065.jpeg',true,65),
('Effortless Co-ord Set','Two-pc set',1850,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p066.jpeg',true,66),
('Everyday Luxe Set','Two-pc set',1850,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p067.jpeg',true,67),
('Cameo Signature Set','Two-pc set',1850,ARRAY['FREE']::text[],'{}'::text[],'assets/products/p068.jpeg',true,68),
('Tailored Everyday Pants','Bottoms',1100,ARRAY['28','30','32']::text[],'{}'::text[],'assets/products/p069.jpeg',true,69),
('City Chic Trousers','Bottoms',1100,ARRAY['28','30','32']::text[],'{}'::text[],'assets/products/p070.jpeg',true,70),
('Relaxed Fit Bottoms','Bottoms',950,ARRAY['26','28','30','32']::text[],'{}'::text[],'assets/products/p071.jpeg',true,71),
('Essential Straight Pants','Bottoms',950,ARRAY['26','28','30','32']::text[],'{}'::text[],'assets/products/p072.jpeg',true,72);
